{{- $infoMetrics := .Values.infoMetrics | default dict }}
{{- if $infoMetrics.enabled }}
{{- $service := $infoMetrics.service | default dict }}
---

# HPE CSI Info Metrics Service
kind: Service
apiVersion: v1
metadata:
  name: hpe-csi-info-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: hpe-csi-info-metrics-service
    {{- range $key, $value := $service.customLabels }}
    {{ $key }}: {{ $value | quote -}}
    {{ end }}
spec:
  {{- $serviceType := $service.type | default "ClusterIP" }}
  type: {{ $serviceType | quote }}
  ports:
    - name: http-metrics
      port: {{ $service.port | default 9090 }}
      {{- if eq $serviceType "NodePort" }}
      {{- if $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      targetPort: 9099
  selector:
    app: hpe-csi-controller
{{- end }}
