{{- if .Values.enableInfoMetrics }}
---

# HPE CSI Info Metrics Service
kind: Service
apiVersion: v1
metadata:
  name: hpe-csi-info-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: hpe-csi-info-metrics-service
    k8s_cluster: us-west-prod-1
spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9099
  selector:
    app: hpe-csi-controller

---
# Service Monitor to enable discovery as a Prometheus scrape target

kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: hpe-csi-info-metrics-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: hpe-csi-info-metrics-service
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 30s
  targetLabels:
    - k8s_cluster
{{- end }}
