# Default values for hpe-csi-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# image pull policy for all images in csi deployment
imagePullPolicy: 'IfNotPresent'

# flavor
flavor: kubernetes

# log level for all csi driver components
logLevel: info

## For controlling automatic iscsi/multipath package installation (default: false)
disableNodeConformance: false

# values for CHAP Authentication
iscsi:
  chapUser: ""
  chapPassword: ""

# registry prefix for hpe csi images
registry: "quay.io"

# HPE CSI info metrics are Prometheus metrics that allow separately provided
# storage system metrics to be correlated with resources managed by the HPE
# CSI Driver.
infoMetrics:
  # When enabled is set to false, other values in this section have no effect.
  enabled: false

  # A Service is created to provide access to the info metrics.
  service:
    # The "ClusterIP" type is appropriate when Prometheus is running within the
    # cluster.  The "NodePort" type can be used if the service must be accessed
    # from outside the cluster.
    type: ClusterIP

    # The port exposed by the info metrics Service within the cluster.
    port: 9090

    # The external node port at which info metrics are served, when the
    # serviceType is NodePort.
    nodePort: 30901

    # Labels to be added to the info metrics Service.  They can be used,
    # for example, to add target labels in a ServiceMonitor scrape
    # configuration.
    #customLabels:
      #k8s_cluster: mycluster

  # When true, a ServiceMonitor is created to enable discovery as a scrape
  # target by a Prometheus Operator running within the cluster.  If set to
  # true when the Prometheus custom resource definitions are not installed,
  # chart installation will be unsuccessful.
  localPrometheusOperator: false
  scrapeInterval: 30s

  # Free-form YAML content to be added to the ServiceMonitor spec, intended to
  # enable a customized Prometheus scrape configuration including target labels
  # and relabeling.
  #scrapeConfig: |-
    #sampleLimit: 10000
    #jobLabel: myjob
    #targetLabels:
    #- k8s_cluster
